version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: emynopass-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/emynopass.db
      - JWT_SECRET=default-jwt-secret-change-in-production
      - PORT=3001
      - FRONTEND_URL=https://emynona.cloud
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend/data:/app/data
    networks:
      - emynopass-network
    command: ["node", "dist/index.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: emynopass-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=https://emynona.cloud
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - emynopass-network
    healthcheck:
      disable: true

  redis:
    image: redis:alpine
    container_name: emynopass-redis
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - emynopass-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: emynopass-nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./docker/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/var/www/uploads:ro
      - ./logs:/var/log/nginx:rw
    depends_on:
      - frontend
      - backend
    networks:
      - emynopass-network

volumes:
  emynopass-data:
  emynopass-uploads:
  emynopass-logs:
  redis-data:

networks:
  emynopass-network:
    driver: bridge
