@echo off
echo 🔧 Test de l'approche séquentielle...

echo 📦 Reconstruction de l'image Docker...
docker-compose build --no-cache backend

echo 🚀 Démarrage du backend avec la nouvelle approche...
docker-compose up backend

echo.
echo 📊 Surveillez les logs pour voir si l'approche séquentielle fonctionne.
echo Vous devriez voir:
echo - 🔧 [DEBUG] Début de l'initialisation séquentielle des tables...
echo - 🔧 [DEBUG] Création de la table users...
echo - ✅ [DEBUG] Table users créée avec succès
echo - 🔧 [DEBUG] Création de la table files...
echo - ✅ [DEBUG] Table files créée avec succès
echo - etc...

pause
